# -*- coding: utf-8 -*-
"""AI_W7_17_03_23_mtcars.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19qVCMHoQKWCDkppIh4aBM3-kK7bOaOgm
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

url = '/mtcars.csv'
data = pd.read_csv(url)
data.head()

data.hist()
plt.show()

sns.pairplot(data)

correlation = data.corr()
print(correlation)

sns.heatmap(correlation, annot = True) #Ve bang co mau

data.plot(kind='scatter', x = 'wt', y = 'mpg', figsize = (9,9), color='black')

### mpg = -5.344*wt + 37.28. PT bac 1 (do chinh xac: 75%) 1 bien

from sklearn import linear_model
model = linear_model.LinearRegression()
model.fit(X = pd.DataFrame(data['wt']), y = data['mpg'])

print('Gia tri intercept: ', model.intercept_)
print('Gia tri coeffient: ', model.coef_)
print('Do chinh xac: ', model.score(X = pd.DataFrame(data['wt']), y = data['mpg']))



data.plot(kind = 'scatter', x='wt', y='mpg', figsize=(9,9), color='black', xlim=(0,7))
y_pred = model.predict(X = pd.DataFrame(data['wt']))
plt.plot(data['wt'], y_pred, color='red')

### pt bac 2 (do chinh xac 82%)
### mpg = 13.38wt + 1.17wt^2 + 49.93

model = linear_model.LinearRegression()
X = pd.DataFrame([data['wt'], data['wt']**2]).T
model.fit(X,y = data['mpg'])
print('Intercept la: ', model.intercept_)
print('Coefficient la:', model.coef_)
print('Do chinh xac: ',model.score(X,y = data['mpg']))

range = np.arange(1.5, 5.5, 0.1)
X_range = pd.DataFrame([range, range**2]).T
y_pred = model.predict(X=X_range)
data.plot(kind='scatter', x='wt', y='mpg', figsize=(9,9), color = 'black', xlim = (0,7))
plt.plot(range, y_pred, color='red')

###pt bac 7

model = linear_model.LinearRegression()
X = pd.DataFrame([data['wt'], data['wt']**2, data['wt']**3, data['wt']**4, data['wt']**5, data['wt']**6, data['wt']**7]).T
model.fit(X,y = data['mpg'])
print('Intercept la: ', model.intercept_)
print('Coefficient la:', model.coef_)
print('Do chinh xac: ',model.score(X,y = data['mpg']))

range = np.arange(1.5, 5.5, 0.1)
X_range = pd.DataFrame([range, range**2, range**3, range**4, range**5, range**6, range**7 ]).T
y_pred = model.predict(X=X_range)
data.plot(kind='scatter', x='wt', y='mpg', figsize=(9,9), color = 'black', xlim = (0,7))
plt.plot(range, y_pred, color='red')

#### pt bac 1 2 bien

model = linear_model.LinearRegression()
model.fit(X=data.loc[:,['wt', 'hp']], y = data['mpg'])
print('Intercept la: ',model.intercept_)
print('Coefficient la: ',model.coef_)
print('Do chinh xac: ', model.score(X=data.loc[:,['wt', 'hp']], y = data['mpg']))

model = linear_model.LinearRegression()
model.fit(X=data.loc[:,['wt', 'hp', 'disp']], y = data['mpg'])
print('Intercept la: ',model.intercept_)
print('Coefficient la: ',model.coef_)
print('Do chinh xac: ', model.score(X=data.loc[:,['wt', 'hp', 'disp']], y = data['mpg']))

